### ISSUE TITLE
Delaunay3D is failing triangulation for some rooms

### ISSUE THREAD

**Issue by Gradir** [vazgriz/DungeonGenerator#8]
I can't wrap my head around this, but Triangulate() method is sometimes failing thus leaving stray, unconnected rooms

![image](https://user-images.githubusercontent.com/6962771/204813625-96595daa-eda7-4c60-aed4-e4b1816ca652.png)

**Comment by Gradir** [comment]
I kind of could go around this with removing the check for AlmostEqual for all triangles
![image](https://user-images.githubusercontent.com/6962771/204816855-5155f3f3-c3e0-484a-b682-23fba3378d4d.png)

**Comment by samuelbigos** [comment]
Hi, I also had this issue when using the library. I believe it's related to the variation in room y position being much smaller than the variation in x and z. I found a somewhat hacky solution which was to add an extra vertex at a high position (i.e if your grid is 64x5x64, add a vertex at 32, 64, 32) so that the bounding box for all the vertices used to triangulate roughly forms a cube. You can then ignore any edges leading to that vertex.

**Comment by Gradir** [comment]
Damn @samuelbigos, nice trick, I will give it a try!

**Comment by vazgriz** [comment]
This is because the 3D triangulation requires a lot of rooms to be on different levels. If the rooms are mostly on the same level, either from having a small height variance, or from having a small number of rooms.

The solution @samuelbigos gives is probably the best way to deal with this if you need it to be 3D. Otherwise you could use the 2D generation code and just make a single room that is 2 levels tall.

**Comment by Gradir** [comment]
This helped with the generation, thanks guys!

**Comment by Snow-Okami** [comment]
How did you implement this fix to solve this situation? I am having trouble doing so.

You can replicate the issue by using seed 977, it will give you a stray room.

I added the following code to my Triangulate function:

`var newHelperPos = new Vector3(size.x / 2f, size.y * 12.8f, size.z / 2f);
 var newHelperPosInt = new Vector3Int((int)newHelperPos.x, (int)newHelperPos.y, (int)newHelperPos.z);
 vertices.Add(new Vertex<Room>(newHelperPosInt, new Room(newHelperPosInt, new Vector3Int(1, 1, 1))));`

The 12.8 was simply the amount @samuelbigos pointed out between the grid's y and the vertex's y.

**Comment by samuelbigos** [comment]
@Snow-Okami I ended up using a more robust solution of putting additional vertices at all 8 corners of a cube encasing my original grid (i.e. take the largest dimension in your grid and form a cube with sides of that length). Then as before just ignore edges leading to those 8 vertices. I haven't encountered stray rooms again using this approach.
